quarkus:
  application:
    name: halo-quarkus
    version: 2.0.0-SNAPSHOT
  
  http:
    port: 8090
    host: 0.0.0.0
  
  log:
    level: INFO
    category:
      run.halo.quarkus: DEBUG

halo:
  work-dir: ${HALO_WORK_DIR:/root/.halo2}
